name: FinMAF
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates
  - libffi=3.4.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.11.11
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  # - vc=14.40
  # - vs2015_runtime
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - altair==5.5.0
      - attrs==24.3.0
      - beautifulsoup4==4.12.3
      - blinker==1.9.0
      - cachetools==5.5.0
      - certifi==2024.12.14
      - cffi==1.17.1
      - charset-normalizer==3.4.0
      - click==8.1.8
      - colorama==0.4.6
      - curl-cffi==0.12.0
      - exchange-calendars==4.6
      - filelock==3.16.1
      - frozendict==2.4.6
      - fsspec==2024.12.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - html5lib==1.1
      - idna==3.10
      - jinja2==3.1.5
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - korean-lunar-calendar==0.3.1
      - lxml==5.3.0
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multitasking==0.0.11
      - narwhals==1.19.1
      - networkx==3.4.2
      - numpy==2.2.1
      - packaging==24.2
      - pandas==2.2.3
      - pandas-market-calendars==4.4.2
      - peewee==3.17.8
      - pillow==11.0.0
      - platformdirs==4.3.6
      - plotly==5.24.1
      - protobuf==5.29.2
      - pyarrow==18.1.0
      - pycparser==2.22
      - pydeck==0.9.1
      - pygments==2.18.0
      - pyluach==2.2.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - referencing==0.35.1
      - requests==2.32.3
      - rich==13.9.4
      - rpds-py==0.22.3
      - scikit-learn==1.6.0
      - scikit-lego==0.9.4
      - scipy==1.14.1
      - six==1.17.0
      - sklego==0.0
      - smmap==5.0.1
      - soupsieve==2.6
      - streamlit==1.41.1
      - sympy==1.13.1
      - tenacity==9.0.0
      - threadpoolctl==3.5.0
      - toml==0.10.2
      - toolz==1.0.0
      - torch==2.5.1
      - tornado==6.4.2
      - tqdm==4.67.1
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - urllib3==2.3.0
      - watchdog==6.0.0
      - webencodings==0.5.1
      - websockets==15.0.1
      - yfinance==0.2.65
