name: Super-Linter

# Trigger the workflow on push or pull requests, but for all branches
on:
  push:
    branches: 
      - '**'  # Applies to every branch
  pull_request:
    branches: 
      - '**'  # Applies to every branch

jobs:
  # Set up the job
  super-lint:
    name: Run Super-Linter
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Run Super-Linter
      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
